Repository HBRS-MAAS/ws18-project-right-brothers, pull requests merged in 2018-11, with the labels that each got.

#8 added customer and order processing agent
  src/main/java/org/right_brothers/Start.java
  src/main/java/org/right_brothers/agents/BakeryCustomerAgent.java
  src/main/java/org/right_brothers/agents/DummyAgent.java
  src/main/java/org/right_brothers/agents/OrderProcessingAgent.java
Labels: needs review

#12 Added customer baker distributed
  README.md
  src/main/java/org/right_brothers/Start.java
  src/main/java/org/right_brothers/agents/BakeryCustomerAgent.java
  src/main/java/org/right_brothers/agents/OrderProcessingAgent.java
Labels: in progress

#14 Assignment 2
  .travis.yml
  README.md
  build.gradle
  docs/Bakery.png
  docs/architecture.pdf
  docs/architecture.tex
  docs/messages.md
  src/main/java/org/right_brothers/README.md
  src/main/java/org/right_brothers/Start.java
  src/main/java/org/right_brothers/agents/BakeryCustomerAgent.java
  src/main/java/org/right_brothers/agents/DummyAgent.java
  src/main/java/org/right_brothers/agents/OrderProcessingAgent.java
  src/main/java/org/yourteamname/Start.java
  src/main/java/org/yourteamname/agents/DummyAgent.java
  src/test/java/org/right_brothers/README.md
Labels: enhancement

#10 added Order and Date object to pass between agents
  build.gradle
  src/main/java/org/right_brothers/Start.java
  src/main/java/org/right_brothers/agents/BakeryCustomerAgent.java
  src/main/java/org/right_brothers/agents/OrderProcessingAgent.java
  src/main/java/org/right_brothers/objects/Date.java
  src/main/java/org/right_brothers/objects/Order.java
Labels: enhancement

#26 Adding Visualization proposal for the project
  docs/Approach1.png
  docs/Approach2.png
  docs/visualization.md
Labels: needs review

#25 Added architecture and edited messages.md
  docs/Bakery.png
  docs/architecture.pdf
  docs/architecture.tex
  docs/messages.md
Labels: needs review

#28 Adding design choice explaination and updating the visualization.md file
  docs/architecture.pdf
  docs/architecture.tex
  docs/visualization.md
Labels: needs review

#30 Assignment 3 (dev to master)
  README.md
  build.gradle
  docs/Approach1.png
  docs/Approach2.png
  docs/Bakery.png
  docs/architecture.pdf
  docs/architecture.tex
  docs/messages.md
  docs/visualization.md
  src/main/java/org/right_brothers/Start.java
  src/main/java/org/right_brothers/agents/BakeryCustomerAgent.java
  src/main/java/org/right_brothers/agents/BaseAgent.java
  src/main/java/org/right_brothers/agents/CoordinatorAgent.java
  src/main/java/org/right_brothers/agents/DummyAgent.java
  src/main/java/org/right_brothers/agents/OrderProcessingAgent.java
  src/main/java/org/right_brothers/data/messages/BakedProduct.java
  src/main/java/org/right_brothers/data/messages/CoordinatorMessage.java
  src/main/java/org/right_brothers/data/messages/Dough.java
  src/main/java/org/right_brothers/data/messages/TimeStep.java
  src/main/java/org/right_brothers/data/messages/UnbakedProduct.java
  src/main/java/org/right_brothers/data/models/Bakery.java
  src/main/java/org/right_brothers/data/models/Batch.java
  src/main/java/org/right_brothers/data/models/Client.java
  src/main/java/org/right_brothers/data/models/Date.java
  src/main/java/org/right_brothers/data/models/DoughPrepTable.java
  src/main/java/org/right_brothers/data/models/Equipment.java
  src/main/java/org/right_brothers/data/models/KneadingMachine.java
  src/main/java/org/right_brothers/data/models/Location.java
  src/main/java/org/right_brothers/data/models/Meta.java
  src/main/java/org/right_brothers/data/models/Order.java
  src/main/java/org/right_brothers/data/models/Oven.java
  src/main/java/org/right_brothers/data/models/Packaging.java
  src/main/java/org/right_brothers/data/models/Product.java
  src/main/java/org/right_brothers/data/models/Recipe.java
  src/main/java/org/right_brothers/data/models/Step.java
  src/main/java/org/right_brothers/objects/ScenarioParser.java
  src/main/java/org/right_brothers/utils/InputParser.java
  src/main/resources/config/100-days/random-scenario.json
  src/main/resources/config/100-days/random-scenario.png
  src/main/resources/config/50-days/random-scenario.json
  src/main/resources/config/50-days/random-scenario.png
  src/main/resources/config/large/random-scenario.json
  src/main/resources/config/large/random-scenario.png
  src/main/resources/config/random/random-scenario.json
  src/main/resources/config/random/random-scenario.png
  src/main/resources/config/sample/bakeries.json
  src/main/resources/config/sample/clients.json
  src/main/resources/config/sample/delivery.json
  src/main/resources/config/sample/meta.json
  src/main/resources/config/sample/street-network.json
  src/main/resources/config/sample/street-network.png
  src/main/resources/config/simple/random-scenario.json
  src/test/java/org/right_brothers/utils/InputParserTest.java
Labels: needs review main

#39 Base agent and Time Keeper agent (basic skeleton)
  src/main/java/org/right_brothers/Start.java
  src/main/java/org/right_brothers/agents/BakeryCustomerAgent.java
  src/main/java/org/right_brothers/agents/BaseAgent.java
  src/main/java/org/right_brothers/agents/OrderProcessingAgent.java
  src/main/java/org/right_brothers/agents/TimeKeeper.java
Labels: enhancement, needs review

#48 Timekeeper and coordinator test combined
  src/main/java/org/right_brothers/Start.java
  src/main/java/org/right_brothers/agents/BakeryCustomerAgent.java
  src/main/java/org/right_brothers/agents/BaseAgent.java
  src/main/java/org/right_brothers/agents/CoordinatorAgent.java
  src/main/java/org/right_brothers/agents/DummyAgent.java
  src/main/java/org/right_brothers/agents/TimeKeeper.java
  src/main/java/org/right_brothers/data/messages/BakedProduct.java
  src/main/java/org/right_brothers/data/messages/CoordinatorMessage.java
  src/main/java/org/right_brothers/data/messages/Dough.java
  src/main/java/org/right_brothers/data/messages/UnbakedProduct.java
Labels: enhancement

#56 Assignment 4 and assignment 5 (dev to master)
  .travis.yml
  src/main/java/org/right_brothers/Start.java
  src/main/java/org/right_brothers/agents/BakeryCustomerAgent.java
  src/main/java/org/right_brothers/agents/BakingStageTester.java
  src/main/java/org/right_brothers/agents/BaseAgent.java
  src/main/java/org/right_brothers/agents/CoolingRackAgent.java
  src/main/java/org/right_brothers/agents/CoordinatorAgent.java
  src/main/java/org/right_brothers/agents/DummyAgent.java
  src/main/java/org/right_brothers/agents/DummyLoadingBayAgent.java
  src/main/java/org/right_brothers/agents/Intermediater.java
  src/main/java/org/right_brothers/agents/OvenManager.java
  src/main/java/org/right_brothers/agents/PackagingStageTester.java
  src/main/java/org/right_brothers/agents/PostBakingProcessor.java
  src/main/java/org/right_brothers/agents/TimeKeeper.java
  src/main/java/org/right_brothers/agents/VisualizationAgent.java
  src/main/java/org/right_brothers/bakery_objects/BakedProduct.java
  src/main/java/org/right_brothers/bakery_objects/ProcessedProduct.java
  src/main/java/org/right_brothers/bakery_objects/Tray.java
  src/main/java/org/right_brothers/bakery_objects/UnbakedProduct.java
  src/main/java/org/right_brothers/data/messages/BakedProduct.java
  src/main/java/org/right_brothers/data/messages/BakedProductMessage.java
  src/main/java/org/right_brothers/data/messages/CompletedProductMessage.java
  src/main/java/org/right_brothers/data/messages/CoordinatorMessage.java
  src/main/java/org/right_brothers/data/messages/Dough.java
  src/main/java/org/right_brothers/data/messages/ProcessedProductMessage.java
  src/main/java/org/right_brothers/data/messages/ProductMessage.java
  src/main/java/org/right_brothers/data/messages/UnbakedProduct.java
  src/main/java/org/right_brothers/data/messages/UnbakedProductMessage.java
  src/main/java/org/right_brothers/data/models/Order.java
  src/main/java/org/right_brothers/objects/CooledProduct.java
  src/main/java/org/right_brothers/utils/Animation.java
  src/main/java/org/right_brothers/utils/ScenarioParser.java
  src/main/resources/config/sample/bakeries.json
Labels: needs review main
