Repository HBRS-MAAS/ws18-project-right-brothers, pull requests merged in 2018-12, with the labels that each got.

#61 updated timekeeper with new time functionality
  src/main/java/org/right_brothers/Start.java
  src/main/java/org/right_brothers/agents/BaseAgent.java
  src/main/java/org/right_brothers/agents/TimeKeeper.java
  src/main/java/org/right_brothers/utils/Time.java
Labels: enhancement

#75 Solved 72
  src/main/java/org/maas/agents/CoolingRackAgent.java
  src/main/java/org/right_brothers/agents/BakingStageTester.java
  src/main/java/org/right_brothers/agents/LoadingBayAgent.java
  src/main/java/org/right_brothers/agents/OvenManager.java
  src/main/java/org/right_brothers/agents/PackagingStageTester.java
  src/main/java/org/right_brothers/agents/PostBakingProcessor.java
  src/main/java/org/right_brothers/agents/PreLoadingProcessor.java
  src/main/java/org/right_brothers/utils/JsonConverter.java
Labels: integration

#77 solved issue 70
  .travis.yml
  build.gradle
  src/main/java/org/maas/BakingStageInitializer.java
  src/main/java/org/maas/PackagingStageInitializer.java
  src/main/java/org/maas/Start.java
  src/main/java/org/maas/agents/DummyAgent.java
Labels: integration

#78 solves issue 76
  src/main/java/org/maas/BakingStageInitializer.java
  src/main/java/org/maas/Start.java
  src/main/java/org/maas/agents/BaseAgent.java
  src/main/java/org/maas/agents/CoolingRackAgent.java
  src/main/java/org/right_brothers/agents/OvenManager.java
  src/main/java/org/right_brothers/agents/PostBakingProcessor.java
Labels: enhancement

#80 Modifying the packaging stage to accept the new loading bay agent from upstream
  src/main/java/org/maas/PackagingStageInitializer.java
  src/main/java/org/maas/Start.java
  src/main/java/org/right_brothers/agents/PackagingStageTester.java
  src/main/java/org/right_brothers/agents/PreLoadingProcessor.java
  src/main/java/org/right_brothers/agents/ProductBoxerAgent.java
  src/main/java/org/right_brothers/data/messages/LoadingBayBox.java
  src/main/java/org/right_brothers/data/messages/LoadingBayMessage.java
  src/main/java/org/right_brothers/data/models/OrderItem.java
  src/main/java/org/right_brothers/data/models/SortByDeliveryTime.java
Labels: enhancement, needs review

#84 Integrated order processing
  .travis.yml
  src/main/java/org/maas/BakingStageInitializer.java
  src/main/java/org/maas/CustomerInitializer.java
  src/main/java/org/maas/Start.java
  src/main/java/org/maas/agents/CoolingRackAgent.java
  src/main/java/org/maas/agents/OrderProcessing.java
  src/main/java/org/maas/agents/TimeKeeper.java
  src/main/java/org/maas/objects/Meta.java
  src/main/java/org/maas/utils/Time.java
  src/main/java/org/right_brothers/agents/DummyOrderProcessor.java
  src/main/java/org/right_brothers/agents/DummyProofer.java
  src/main/java/org/right_brothers/agents/OvenManager.java
  src/main/java/org/right_brothers/agents/PostBakingProcessor.java
  src/main/java/org/right_brothers/agents/PreLoadingProcessor.java
  src/main/java/org/right_brothers/agents/ProductBoxerAgent.java
  src/main/java/org/right_brothers/data/models/Order.java
  src/main/java/org/right_brothers/utils/InputParser.java
Labels: bug, enhancement, integration
